### ISSUE TITLE
README is not in sync with code

### ISSUE THREAD

**Issue by neckert** [uwefassnacht/device-simulator-for-ibm-iot#1]
The description in the README regarding how to run the application locally is not in sync with the latest version of app.js. According to what I can see in app.js, the .env file needs to specify all of the following properties: iotf_org, iotf_id, iotf_authtoken, iotf_type. However, the descriptions just states that you need to store the organization name in the .env file.

**Comment by uwefassnacht** [comment]
Fixed. Thanks for reporting!
