### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by michaelbeck** [uwefassnacht/device-simulator-for-ibm-iot#2]
When doing npm install on windows I first had to install python in the correct version, which is not described in installation instructions.

After that I get the below error at npm install.

When starting the app, I get
Server started on http://localhost:6002
the following line repeats again and again:
Iotfclient is offline. Retrying connection
## npm install error:

C:\data\BlueMix\Code\device-simulator-for-ibm-iot>npm install

> bufferutil@1.2.1 install C:\data\BlueMix\Code\device-simulator-for-ibm-iot\nod
> e_modules\bufferutil
> node-gyp rebuild

C:\data\BlueMix\Code\device-simulator-for-ibm-iot\node_modules\bufferutil>if not
 defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin
\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (nod
e  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\data\BlueMix\Code\device-simulator-for-ibm-iot\nod
e_modules\bufferutil\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodej
s\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\data\BlueMix\Code\device-simulator-for-ibm-iot\node_modules\buff
erutil
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install C:\data\BlueMix\Code\device-simulator-for-ibm-iot
> \node_modules\utf-8-validate
> node-gyp rebuild

C:\data\BlueMix\Code\device-simulator-for-ibm-iot\node_modules\utf-8-validate>if
 not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm
\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else
(node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
 To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visua
l Studio 2005 or 3) add the location of the component to the system path if it
is installed elsewhere.  [C:\data\BlueMix\Code\device-simulator-for-ibm-iot\nod
e_modules\utf-8-validate\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodej
s\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\data\BlueMix\Code\device-simulator-for-ibm-iot\node_modules\utf-
8-validate
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp re
build`
npm WARN install:utf-8-validate@1.2.1 Exit status 1
npm WARN EPACKAGEJSON device-simulator-for-ibm-iot-starter-kit@0.0.1 No reposito
ry field.
npm WARN EPACKAGEJSON device-simulator-for-ibm-iot-starter-kit@0.0.1 license sho
uld be a valid SPDX license expression

**Comment by uwefassnacht** [comment]
Not sure about the npm install issue on Windows (I don't have a Windows machine to try it on). 

The repeating "Iotfclient is offline. Retrying connection" message is probably due to not having an IoT Foundation service instantiated that the simulator can connect to.

**Comment by uwefassnacht** [comment]
Found this thread, which might be related to the npm install issue on Windows: http://stackoverflow.com/questions/17496189/error-in-installing-node-js-module-using-npm

**Comment by michaelbeck** [comment]
The device simulator also works on windoews, the installation issues don't affect functionality.

My problem with both windows and Bluemix was that I registered the IoT Foundation service in Bluemix stage1 which the simulator can't connect to.
