### ISSUE TITLE
Does not work on Bluemix

### ISSUE THREAD

**Issue by michaelbeck** [uwefassnacht/device-simulator-for-ibm-iot#3]
Tried to push the app to Bluemix but don't get any events from the simulator.
## Here's the log from the Bluemix app (looks very similar to windows):

2016-02-10T15:55:28.802+0100
[API/0]
out
Created app with guid d9798d99-b8fb-4724-8d39-0dd2f8264573
2016-02-10T15:56:17.201+0100
[API/1]
out
Updated app with guid d9798d99-b8fb-4724-8d39-0dd2f8264573 ({"name"=>"beckm-device-simulator-for-ibm-iot", "command"=>"PRIVATE DATA HIDDEN", "instances"=>1, "memory"=>256, "disk_quota"=>1024, "buildpack"=>"sdk-for-nodejs", "environment_json"=>"PRIVATE DATA HIDDEN"})
2016-02-10T15:56:26.114+0100
[API/5]
out
Updated app with guid d9798d99-b8fb-4724-8d39-0dd2f8264573 ({"route"=>"e44c11d4-00cf-4320-b351-cb82d28c996f"})
2016-02-10T15:56:47.465+0100
[DEA/8]
out
Got staging request for app with id d9798d99-b8fb-4724-8d39-0dd2f8264573
2016-02-10T15:56:54.631+0100
[API/0]
out
Updated app with guid d9798d99-b8fb-4724-8d39-0dd2f8264573 ({"state"=>"STARTED"})
2016-02-10T15:56:54.861+0100
[STG/8]
out
-----> Downloaded app package (12K)
2016-02-10T15:56:55.075+0100
[STG/0]
out
-----> IBM SDK for Node.js Buildpack v3.0-20160125-1224
2016-02-10T15:56:55.075+0100
[STG/0]
out
2016-02-10T15:56:55.080+0100
[STG/0]
out
Based on Cloud Foundry Node.js Buildpack v1.5.4
2016-02-10T15:56:55.087+0100
[STG/0]
out
-----> Creating runtime environment
2016-02-10T15:56:55.102+0100
[STG/0]
out
NPM_CONFIG_PRODUCTION=true
2016-02-10T15:56:55.102+0100
[STG/0]
out
NPM_CONFIG_LOGLEVEL=error
2016-02-10T15:56:55.107+0100
[STG/0]
out
NODE_ENV=production
2016-02-10T15:56:55.107+0100
[STG/0]
out
NODE_MODULES_CACHE=true
2016-02-10T15:56:55.110+0100
[STG/0]
out
-----> Installing binaries
2016-02-10T15:56:55.135+0100
[STG/0]
out
engines.node (package.json): unspecified
2016-02-10T15:56:55.136+0100
[STG/0]
out
engines.npm (package.json): unspecified (use default)
2016-02-10T15:56:55.141+0100
[STG/0]
out
Resolving node version (latest stable) via 'node-version-resolver'
2016-02-10T15:56:55.358+0100
[STG/0]
out
Installing IBM SDK for Node.js (4.2.4) from cache
2016-02-10T15:56:56.549+0100
[STG/0]
out
Using default npm version: 2.14.12
2016-02-10T15:56:56.804+0100
[STG/0]
out
-----> Restoring cache
2016-02-10T15:56:57.084+0100
[STG/0]
out
Skipping cache restore (new runtime signature)
2016-02-10T15:56:57.086+0100
[STG/0]
out
-----> Building dependencies
2016-02-10T15:56:57.088+0100
[STG/0]
out
Pruning any extraneous modules
2016-02-10T15:56:57.715+0100
[STG/0]
out
Installing node modules (package.json)
2016-02-10T15:57:05.086+0100
[STG/0]
out

> utf-8-validate@1.2.1 install /tmp/staged/app/node_modules/ibmiotf/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/utf-8-validate
> 2016-02-10T15:57:05.086+0100
> [STG/0]
> out
> node-gyp rebuild
> 2016-02-10T15:57:06.923+0100
> [STG/0]
> out
> make: Entering directory `/tmp/staged/app/node_modules/ibmiotf/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/utf-8-validate/build'
> 2016-02-10T15:57:06.925+0100
> [STG/0]
> out
> CXX(target) Release/obj.target/validation/src/validation.o
> 2016-02-10T15:57:07.886+0100
> [STG/0]
> out
> SOLINK_MODULE(target) Release/obj.target/validation.node
> 2016-02-10T15:57:07.960+0100
> [STG/0]
> out
> COPY Release/validation.node
> 2016-02-10T15:57:07.979+0100
> [STG/0]
> out
> make: Leaving directory`/tmp/staged/app/node_modules/ibmiotf/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/utf-8-validate/build'
> 2016-02-10T15:57:08.001+0100
> [STG/0]
> out
> bufferutil@1.2.1 install /tmp/staged/app/node_modules/ibmiotf/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/bufferutil
> 2016-02-10T15:57:08.002+0100
> [STG/0]
> out
> node-gyp rebuild
> 2016-02-10T15:57:08.855+0100
> [STG/0]
> out
> make: Entering directory `/tmp/staged/app/node_modules/ibmiotf/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/bufferutil/build'
> 2016-02-10T15:57:08.856+0100
> [STG/0]
> out
> CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
> 2016-02-10T15:57:09.873+0100
> [STG/0]
> out
> SOLINK_MODULE(target) Release/obj.target/bufferutil.node
> 2016-02-10T15:57:09.951+0100
> [STG/0]
> out
> COPY Release/bufferutil.node
> 2016-02-10T15:57:09.965+0100
> [STG/0]
> out
> make: Leaving directory`/tmp/staged/app/node_modules/ibmiotf/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/bufferutil/build'
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> ├── parseurl@1.3.1
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> ├── etag@1.7.0
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> ├── utils-merge@1.0.0
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> ├── fresh@0.3.0
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> ├── methods@1.1.2
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> ├── array-flatten@1.1.1
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> ├── cookie-signature@1.0.6
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> ├── escape-html@1.0.3
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> ├── range-parser@1.0.3
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> ├── cookie@0.1.5
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> ├── content-type@1.0.1
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> express@4.13.4 node_modules/express
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> ├── merge-descriptors@1.0.1
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> ├── serve-static@1.10.2
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> ├── path-to-regexp@0.1.7
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> ├── vary@1.0.1
> 2016-02-10T15:57:10.451+0100
> [STG/0]
> out
> dotenv@1.2.0 node_modules/dotenv
> 2016-02-10T15:57:10.452+0100
> [STG/0]
> out
> ├── depd@1.1.0
> 2016-02-10T15:57:10.452+0100
> [STG/0]
> out
> ├── content-disposition@0.5.1
> 2016-02-10T15:57:10.453+0100
> [STG/0]
> out
> ├── qs@4.0.0
> 2016-02-10T15:57:10.454+0100
> [STG/0]
> out
> ├── on-finished@2.3.0 (ee-first@1.1.1)
> 2016-02-10T15:57:10.454+0100
> [STG/0]
> out
> ├── finalhandler@0.4.1 (unpipe@1.0.0)
> 2016-02-10T15:57:10.455+0100
> [STG/0]
> out
> ├── debug@2.2.0 (ms@0.7.1)
> 2016-02-10T15:57:10.456+0100
> [STG/0]
> out
> ├── proxy-addr@1.0.10 (forwarded@0.1.0, ipaddr.js@1.0.5)
> 2016-02-10T15:57:10.457+0100
> [STG/0]
> out
> ├── send@0.13.1 (destroy@1.0.4, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
> 2016-02-10T15:57:10.458+0100
> [STG/0]
> out
> ├── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.9)
> 2016-02-10T15:57:10.458+0100
> [STG/0]
> out
> └── type-is@1.6.11 (media-typer@0.3.0, mime-types@2.1.9)
> 2016-02-10T15:57:10.459+0100
> [STG/0]
> out
> cfenv@1.0.3 node_modules/cfenv
> 2016-02-10T15:57:10.460+0100
> [STG/0]
> out
> ├── ports@1.1.0
> 2016-02-10T15:57:10.460+0100
> [STG/0]
> out
> ├── underscore@1.8.3
> 2016-02-10T15:57:10.462+0100
> [STG/0]
> out
> └── js-yaml@3.4.6 (inherit@2.2.3, esprima@2.7.2, argparse@1.0.6)
> 2016-02-10T15:57:10.463+0100
> [STG/0]
> out
> ├── btoa@1.1.2
> 2016-02-10T15:57:10.463+0100
> [STG/0]
> out
> ibmiotf@0.2.10 node_modules/ibmiotf
> 2016-02-10T15:57:10.463+0100
> [STG/0]
> out
> ├── format@0.2.2
> 2016-02-10T15:57:10.463+0100
> [STG/0]
> out
> ├── events@1.1.0
> 2016-02-10T15:57:10.464+0100
> [STG/0]
> out
> ├── loglevel@1.4.0
> 2016-02-10T15:57:10.464+0100
> [STG/0]
> out
> ├── bluebird@2.10.2
> 2016-02-10T15:57:10.465+0100
> [STG/0]
> out
> ├── axios@0.5.4 (es6-promise@2.3.0)
> 2016-02-10T15:57:10.465+0100
> [STG/0]
> out
> └── mqtt@1.5.0 (inherits@2.0.1, xtend@4.0.1, minimist@1.2.0, commist@1.0.0, readable-stream@1.0.33, mqtt-connection@2.1.1, mqtt-packet@3.4.6, end-of-stream@1.1.0, concat-stream@1.5.1, help-me@0.1.0, websocket-stream@2.3.0)
> 2016-02-10T15:57:10.562+0100
> [STG/0]
> out
> -----> Installing App Management
> 2016-02-10T15:57:10.617+0100
> [STG/0]
> out
> To install App Management utilities, specify your 'node' start script in 'package.json' or 'Procfile'.
> 2016-02-10T15:57:10.617+0100
> [STG/0]
> out
> -----> Caching build
> 2016-02-10T15:57:10.617+0100
> [STG/0]
> out
> WARN: App Management cannot be installed because the start script cannot be found.
> 2016-02-10T15:57:10.650+0100
> [STG/0]
> out
> Clearing previous node cache
> 2016-02-10T15:57:10.657+0100
> [STG/0]
> out
> Saving 2 cacheDirectories (default):
> 2016-02-10T15:57:10.658+0100
> [STG/0]
> out
> - node_modules
>   2016-02-10T15:57:11.103+0100
>   [STG/0]
>   out
> - bower_components (nothing to cache)
>   2016-02-10T15:57:11.450+0100
>   [STG/0]
>   out
>   -----> Build succeeded!
>   2016-02-10T15:57:12.089+0100
>   [STG/0]
>   out
>   ├── cfenv@1.0.3
>   2016-02-10T15:57:12.089+0100
>   [STG/0]
>   out
>   ├── express@4.13.4
>   2016-02-10T15:57:12.089+0100
>   [STG/0]
>   out
>   └── ibmiotf@0.2.10
>   2016-02-10T15:57:12.089+0100
>   [STG/0]
>   out
>   ├── dotenv@1.2.0
>   2016-02-10T15:57:12.115+0100
>   [STG/0]
>   err
>   2016-02-10T15:57:16.527+0100
>   [STG/8]
>   out
>   -----> Uploading droplet (15M)
>   2016-02-10T15:57:23.405+0100
>   [DEA/8]
>   out
>   Starting app instance (index 0) with guid d9798d99-b8fb-4724-8d39-0dd2f8264573
>   2016-02-10T15:57:33.237+0100
>   [App/0]
>   out
>   2016-02-10T15:57:33.239+0100
>   [App/0]
>   out
>   --- DEBUG appENV: ---
>   2016-02-10T15:57:33.246+0100
>   [App/0]
>   out
>   AppEnv {
>   2016-02-10T15:57:33.246+0100
>   [App/0]
>   out
>   app:
>   2016-02-10T15:57:33.246+0100
>   [App/0]
>   out
>   isLocal: false,
>   2016-02-10T15:57:33.246+0100
>   [App/0]
>   out
>   { limits: { mem: 256, disk: 1024, fds: 16384 },
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   started_at: '2016-02-10 14:57:23 +0000',
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   host: '0.0.0.0',
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   application_name: 'beckm-device-simulator-for-ibm-iot',
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   start: '2016-02-10 14:57:23 +0000',
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   url: 'https://beckm-device-simulator-for-ibm-iot.stage1.mybluemix.net' }
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   application_uris: [ 'beckm-device-simulator-for-ibm-iot.stage1.mybluemix.net' ],
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   uris: [ 'beckm-device-simulator-for-ibm-iot.stage1.mybluemix.net' ],
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   application_version: '089ffbda-d7d9-4ece-8a36-83fa55af0be1',
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   services: {},
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   started_at_timestamp: 1455116243,
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   instance_index: 0,
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   instance_id: '1f4bc956e9b6478e8b3f1c7801293d6b',
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   state_timestamp: 1455116243 },
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   port: 62706,
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   version: '089ffbda-d7d9-4ece-8a36-83fa55af0be1',
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   space_id: '83006265-e2f0-457a-9426-e5a87ed01597',
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   port: 62706,
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   bind: '0.0.0.0',
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   space_name: 'dev',
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   name: 'beckm-device-simulator-for-ibm-iot',
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   name: 'beckm-device-simulator-for-ibm-iot',
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   users: null,
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   application_id: 'd9798d99-b8fb-4724-8d39-0dd2f8264573',
>   2016-02-10T15:57:33.247+0100
>   [App/0]
>   out
>   urls: [ 'https://beckm-device-simulator-for-ibm-iot.stage1.mybluemix.net' ],
>   2016-02-10T15:57:33.257+0100
>   [App/0]
>   out
>   'auth-token': 'token123',
>   2016-02-10T15:57:33.257+0100
>   [App/0]
>   out
>   'auth-method': 'token' }
>   2016-02-10T15:57:33.257+0100
>   [App/0]
>   out
>   --- DEBUG iotConfig: ---
>   2016-02-10T15:57:33.257+0100
>   [App/0]
>   out
>   id: 'beckmsIoTDev1',
>   2016-02-10T15:57:33.257+0100
>   [App/0]
>   out
>   type: 'beckmsIoTDev',
>   2016-02-10T15:57:33.257+0100
>   [App/0]
>   out
>   { org: '83pi74',
>   2016-02-10T15:57:33.312+0100
>   [App/0]
>   out
>   Server started on https://beckm-device-simulator-for-ibm-iot.stage1.mybluemix.net
>   2016-02-10T15:57:33.326+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T15:57:36.338+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T15:57:39.350+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T15:57:42.365+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T15:57:45.376+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T15:57:55.398+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T15:58:05.523+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T15:58:15.537+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T15:58:25.552+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T15:58:35.568+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T16:04:36.543+0100
>   [API/5]
>   out
>   Updated app with guid d9798d99-b8fb-4724-8d39-0dd2f8264573 ({"name"=>"beckm-device-simulator-for-ibm-iot", "command"=>"PRIVATE DATA HIDDEN", "instances"=>1, "memory"=>256, "disk_quota"=>1024, "buildpack"=>"sdk-for-nodejs", "environment_json"=>"PRIVATE DATA HIDDEN"})
>   2016-02-10T16:04:58.163+0100
>   [API/0]
>   out
>   Updated app with guid d9798d99-b8fb-4724-8d39-0dd2f8264573 ({"state"=>"STOPPED"})
>   2016-02-10T16:04:59.335+0100
>   [DEA/8]
>   out
>   Stopped app instance (index 0) with guid d9798d99-b8fb-4724-8d39-0dd2f8264573
>   2016-02-10T16:04:59.335+0100
>   [DEA/8]
>   out
>   Stopping app instance (index 0) with guid d9798d99-b8fb-4724-8d39-0dd2f8264573
>   2016-02-10T16:05:02.851+0100
>   [DEA/83]
>   out
>   Got staging request for app with id d9798d99-b8fb-4724-8d39-0dd2f8264573
>   2016-02-10T16:05:10.053+0100
>   [API/0]
>   out
>   Updated app with guid d9798d99-b8fb-4724-8d39-0dd2f8264573 ({"state"=>"STARTED"})
>   2016-02-10T16:05:10.277+0100
>   [STG/83]
>   out
>   -----> Downloaded app package (12K)
>   2016-02-10T16:05:12.319+0100
>   [STG/83]
>   out
>   -----> Downloaded app buildpack cache (1.9M)
>   2016-02-10T16:05:12.551+0100
>   [STG/0]
>   out
>   -----> IBM SDK for Node.js Buildpack v3.0-20160125-1224
>   2016-02-10T16:05:12.551+0100
>   [STG/0]
>   out
>   2016-02-10T16:05:12.556+0100
>   [STG/0]
>   out
>   Based on Cloud Foundry Node.js Buildpack v1.5.4
>   2016-02-10T16:05:12.563+0100
>   [STG/0]
>   out
>   -----> Creating runtime environment
>   2016-02-10T16:05:12.577+0100
>   [STG/0]
>   out
>   NPM_CONFIG_LOGLEVEL=error
>   2016-02-10T16:05:12.577+0100
>   [STG/0]
>   out
>   NPM_CONFIG_PRODUCTION=true
>   2016-02-10T16:05:12.582+0100
>   [STG/0]
>   out
>   NODE_MODULES_CACHE=true
>   2016-02-10T16:05:12.582+0100
>   [STG/0]
>   out
>   NODE_ENV=production
>   2016-02-10T16:05:12.584+0100
>   [STG/0]
>   out
>   -----> Installing binaries
>   2016-02-10T16:05:12.608+0100
>   [STG/0]
>   out
>   engines.node (package.json): unspecified
>   2016-02-10T16:05:12.609+0100
>   [STG/0]
>   out
>   engines.npm (package.json): unspecified (use default)
>   2016-02-10T16:05:12.612+0100
>   [STG/0]
>   out
>   Resolving node version (latest stable) via 'node-version-resolver'
>   2016-02-10T16:05:12.872+0100
>   [STG/0]
>   out
>   Installing IBM SDK for Node.js (4.2.4) from cache
>   2016-02-10T16:05:13.951+0100
>   [STG/0]
>   out
>   Using default npm version: 2.14.12
>   2016-02-10T16:05:14.269+0100
>   [STG/0]
>   out
>   -----> Restoring cache
>   2016-02-10T16:05:14.624+0100
>   [STG/0]
>   out
>   Loading 2 from cacheDirectories (default):
>   2016-02-10T16:05:14.625+0100
>   [STG/0]
>   out
> - node_modules
>   2016-02-10T16:05:14.635+0100
>   [STG/0]
>   out
> - bower_components (not cached - skipping)
>   2016-02-10T16:05:14.637+0100
>   [STG/0]
>   out
>   -----> Building dependencies
>   2016-02-10T16:05:14.640+0100
>   [STG/0]
>   out
>   Pruning any extraneous modules
>   2016-02-10T16:05:15.932+0100
>   [STG/0]
>   out
>   Installing node modules (package.json)
>   2016-02-10T16:05:17.357+0100
>   [STG/0]
>   out
>   -----> Installing App Management
>   2016-02-10T16:05:17.394+0100
>   [STG/0]
>   out
>   WARN: App Management cannot be installed because the start script cannot be found.
>   2016-02-10T16:05:17.395+0100
>   [STG/0]
>   out
>   To install App Management utilities, specify your 'node' start script in 'package.json' or 'Procfile'.
>   2016-02-10T16:05:17.395+0100
>   [STG/0]
>   out
>   -----> Caching build
>   2016-02-10T16:05:17.414+0100
>   [STG/0]
>   out
>   Clearing previous node cache
>   2016-02-10T16:05:17.421+0100
>   [STG/0]
>   out
>   Saving 2 cacheDirectories (default):
>   2016-02-10T16:05:17.422+0100
>   [STG/0]
>   out
> - node_modules
>   2016-02-10T16:05:17.855+0100
>   [STG/0]
>   out
> - bower_components (nothing to cache)
>   2016-02-10T16:05:18.197+0100
>   [STG/0]
>   out
>   -----> Build succeeded!
>   2016-02-10T16:05:19.046+0100
>   [STG/0]
>   out
>   ├── cfenv@1.0.3
>   2016-02-10T16:05:19.046+0100
>   [STG/0]
>   out
>   ├── dotenv@1.2.0
>   2016-02-10T16:05:19.046+0100
>   [STG/0]
>   out
>   └── ibmiotf@0.2.10
>   2016-02-10T16:05:19.046+0100
>   [STG/0]
>   out
>   ├── express@4.13.4
>   2016-02-10T16:05:19.088+0100
>   [STG/0]
>   err
>   2016-02-10T16:05:24.582+0100
>   [STG/83]
>   out
>   -----> Uploading droplet (15M)
>   2016-02-10T16:05:30.705+0100
>   [DEA/83]
>   out
>   Starting app instance (index 0) with guid d9798d99-b8fb-4724-8d39-0dd2f8264573
>   2016-02-10T16:05:41.056+0100
>   [App/0]
>   out
>   2016-02-10T16:05:41.057+0100
>   [App/0]
>   out
>   --- DEBUG appENV: ---
>   2016-02-10T16:05:41.063+0100
>   [App/0]
>   out
>   space_id: '83006265-e2f0-457a-9426-e5a87ed01597',
>   2016-02-10T16:05:41.063+0100
>   [App/0]
>   out
>   AppEnv {
>   2016-02-10T16:05:41.063+0100
>   [App/0]
>   out
>   app:
>   2016-02-10T16:05:41.063+0100
>   [App/0]
>   out
>   name: 'beckm-device-simulator-for-ibm-iot',
>   2016-02-10T16:05:41.063+0100
>   [App/0]
>   out
>   application_name: 'beckm-device-simulator-for-ibm-iot',
>   2016-02-10T16:05:41.063+0100
>   [App/0]
>   out
>   { limits: { mem: 256, disk: 1024, fds: 16384 },
>   2016-02-10T16:05:41.063+0100
>   [App/0]
>   out
>   uris: [ 'beckm-device-simulator-for-ibm-iot.stage1.mybluemix.net' ],
>   2016-02-10T16:05:41.063+0100
>   [App/0]
>   out
>   application_uris: [ 'beckm-device-simulator-for-ibm-iot.stage1.mybluemix.net' ],
>   2016-02-10T16:05:41.063+0100
>   [App/0]
>   out
>   isLocal: false,
>   2016-02-10T16:05:41.063+0100
>   [App/0]
>   out
>   version: '728510cb-fb4e-4249-8827-96bbe0f5775d',
>   2016-02-10T16:05:41.063+0100
>   [App/0]
>   out
>   application_version: '728510cb-fb4e-4249-8827-96bbe0f5775d',
>   2016-02-10T16:05:41.063+0100
>   [App/0]
>   out
>   application_id: 'd9798d99-b8fb-4724-8d39-0dd2f8264573',
>   2016-02-10T16:05:41.063+0100
>   [App/0]
>   out
>   space_name: 'dev',
>   2016-02-10T16:05:41.064+0100
>   [App/0]
>   out
>   users: null,
>   2016-02-10T16:05:41.064+0100
>   [App/0]
>   out
>   port: 64161,
>   2016-02-10T16:05:41.064+0100
>   [App/0]
>   out
>   start: '2016-02-10 15:05:30 +0000',
>   2016-02-10T16:05:41.064+0100
>   [App/0]
>   out
>   instance_id: 'fc7d3c34860f410686c558b9ec20bb7a',
>   2016-02-10T16:05:41.064+0100
>   [App/0]
>   out
>   started_at: '2016-02-10 15:05:30 +0000',
>   2016-02-10T16:05:41.064+0100
>   [App/0]
>   out
>   started_at_timestamp: 1455116730,
>   2016-02-10T16:05:41.064+0100
>   [App/0]
>   out
>   bind: '0.0.0.0',
>   2016-02-10T16:05:41.064+0100
>   [App/0]
>   out
>   instance_index: 0,
>   2016-02-10T16:05:41.064+0100
>   [App/0]
>   out
>   name: 'beckm-device-simulator-for-ibm-iot',
>   2016-02-10T16:05:41.064+0100
>   [App/0]
>   out
>   port: 64161,
>   2016-02-10T16:05:41.064+0100
>   [App/0]
>   out
>   urls: [ 'https://beckm-device-simulator-for-ibm-iot.stage1.mybluemix.net' ],
>   2016-02-10T16:05:41.064+0100
>   [App/0]
>   out
>   url: 'https://beckm-device-simulator-for-ibm-iot.stage1.mybluemix.net' }
>   2016-02-10T16:05:41.064+0100
>   [App/0]
>   out
>   state_timestamp: 1455116730 },
>   2016-02-10T16:05:41.064+0100
>   [App/0]
>   out
>   services: {},
>   2016-02-10T16:05:41.064+0100
>   [App/0]
>   out
>   host: '0.0.0.0',
>   2016-02-10T16:05:41.074+0100
>   [App/0]
>   out
>   --- DEBUG iotConfig: ---
>   2016-02-10T16:05:41.074+0100
>   [App/0]
>   out
>   'auth-method': 'token' }
>   2016-02-10T16:05:41.074+0100
>   [App/0]
>   out
>   type: 'beckm-iot-simulator-bluemix',
>   2016-02-10T16:05:41.074+0100
>   [App/0]
>   out
>   { org: '83pi74',
>   2016-02-10T16:05:41.074+0100
>   [App/0]
>   out
>   id: 'beckm-iot-simulator-01',
>   2016-02-10T16:05:41.074+0100
>   [App/0]
>   out
>   'auth-token': 'FE1yBlB2-OGw0VS64H',
>   2016-02-10T16:05:41.124+0100
>   [App/0]
>   out
>   Server started on https://beckm-device-simulator-for-ibm-iot.stage1.mybluemix.net
>   2016-02-10T16:05:41.133+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T16:05:44.213+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T16:05:47.232+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T16:05:50.239+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T16:05:53.246+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T16:06:03.251+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T16:06:13.259+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T16:06:23.275+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T16:06:33.291+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection
>   2016-02-10T16:06:43.308+0100
>   [App/0]
>   err
>   Iotfclient is offline. Retrying connection

**Comment by uwefassnacht** [comment]
Judging from the logs, it looks like you have not registered the device simulator in your IoT Foundation service on Bluemix (that's why you are getting the "Iotfclient is offline" message). Please have a look at the README and make sure the simulator is registered. 

If that does not fix the issue, please reopen it.
